global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    cluster: a
rule_files:
  - recording_rules.yml
scrape_configs:
  - job_name: 'demo'
    static_configs:
      - targets:
        - 'd1:8081'
        - 'd2:8080'
        - 'd3:8080'
